### PR TITLE
Lualatex

### PR DESCRIPTION
**Pull request by freebroccolo**
You can typeset this in the same way as with pdflatex:

```bash
$ lualatex draft
$ bibtex draft
$ lualatex draft
$ lualatex draft
```

It also uses `TeX Gyre Pagella` (a Palatino clone) for prose, `XITS Math` for default math and `Unifraktur Maguntia` for the fraktur ranges. If you typeset with `pdflatex` instead of `lualatex` it should look the same as before.

### CODE REVIEW

**Comment by jonsterling** [comment]
thanks!

By the way, regarding that weird fontspec + colors thing that we were talking about that, were we actually setting colors with fontspec in that paper before which Bob couldn't read? I don't think we were, but the pdf had come out all garbled for him.

**Comment by jonsterling** [comment]
Oh, and I probably need to install this unifraktur font on my machine, right?

**Comment by freebroccolo** [comment]
Regarding the rendering issue, I don't remember for sure if we were setting the colors that way or not. Might have done it that way in one of the diagrams or something. There is also some weird issues that pop up sometimes in Acrobat with pgf/tikz diagrams that use transparency though, and I think I might have used that somehow in some of the fancier diagrams. I think as long as you check the final output in `PDF.js` (opening with Chrome or Firefox would be enough) and Acrobat you should spot any issues. They should be rare, but who knows I guess…

And yeah, for the fraktur font, it's enough to open the OSX font book app and install the font file that way. You may need to restart your shell and/or run `luaotfload-tool --update --force` afterwards just to be sure it shows up when you run `lualatex`.

**Comment by freebroccolo** [comment]
The `luaotfload-tool` command may take a few minutes to complete btw.

**Comment by jonsterling** [comment]
@freebroccolo The odd thing about the rendering issue was that it always showed up fine in the GitHub preview, which makes me think that maybe there is a separate problem beyond the one that you found working on the book, which (so far) we have only observed on Bob's machine... 😦 

But since it looks like I can still always just make a build using `pdflatex` for anyone who has trouble, just degrading the nice fonts a bit, that's fine. I've never had trouble viewing any document made with `lualatex`.

**Comment by freebroccolo** [comment]
Also, it may be the case that you'd want to adjust/remove manual spacing adjustments that you'd made for `pdflatex`, since the renderer should be significantly better about spacing already now and may overcompensate otherwise.

**Comment by jonsterling** [comment]
Oh, that's great news! I've hated having to make stupid little adjustments...

**Pull request merged**
